import './App.css';
import BasicTableComponent from './components/basic.table';
import ColapseColTable from './components/colapseCol.table';
import FinalTableComponent from './components/finalTable';
import React from 'react';

function App() {
  const testData = React.useMemo(() => [
    {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    }, {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    }, {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    }, {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    }, {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    }, {
      "firstName": "horn-od926",
      "lastName": "selection-gsykp",
      "age": 22,
      "visits": 20,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "heart-nff6w",
      "lastName": "information-nyp92",
      "age": 16,
      "visits": 98,
      "progress": 40,
      "status": "complicated",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "minute-yri12",
      "lastName": "fairies-iutct",
      "age": 7,
      "visits": 77,
      "progress": 39,
      "status": "single",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
    {
      "firstName": "degree-jx4h0",
      "lastName": "man-u2y40",
      "age": 27,
      "visits": 54,
      "progress": 92,
      "status": "relationship",
      "section1": 1,
      "section2": 2,
      "section3": 3,
      "section4": 4,
      "section5": 5,
      "section6": 6,
      "section7": 7,
      "section8": 8,
      "section9": 9,
      "section10": 10,
      "section11": 11,
      "section12": 12,
      "section13": 13,
      "section14": 14,
    },
  ], []);

  const finalData = React.useMemo(() => [/*some data here*/], []);

  const testColumns = React.useMemo(() => [
    {
      Header: 'Name',
      columns: [
        {
          Header: 'First Name',
          accessor: 'firstName',
        },
        {
          Header: 'Last Name',
          accessor: 'lastName',
        },
      ],
    },
    {
      Header: 'Info',
      columns: [
        {
          Header: 'Age',
          accessor: 'age',
        },
        {
          Header: 'Visits',
          accessor: 'visits',
        },
        {
          Header: 'Status',
          accessor: 'status',
        },
        {
          Header: 'Profile Progress',
          accessor: 'progress',
        },
      ],
    },
    {
      Header: 'Other',
      columns: [
        {
          Header: 'Section 1',
          accessor: 'section1',
        },
        {
          Header: 'Section 2',
          accessor: 'section2',
        },
        {
          Header: 'Section 3',
          accessor: 'section3',
        },
        {
          Header: 'Section 4',
          accessor: 'section4',
        },
        {
          Header: 'Section 5',
          accessor: 'section5',
        },
        {
          Header: 'Section 6',
          accessor: 'section6',
        },
        {
          Header: 'Section 7',
          accessor: 'section7',
        },
        {
          Header: 'Section 8',
          accessor: 'section8',
        },
        {
          Header: 'Section 9',
          accessor: 'section9',
        },
        {
          Header: 'Section 10',
          accessor: 'section10',
        },
        {
          Header: 'Section 11',
          accessor: 'section11',
        },
        {
          Header: 'Section 12',
          accessor: 'section12',
        },
        {
          Header: 'Section 13',
          accessor: 'section13',
        },
        {
          Header: 'Section 14',
          accessor: 'section14',
        },
      ],
    },
  ], []);

  const finalColumns = React.useMemo(() => [
    {
      Header: 'Suite Name',
      accessor: 'dummyObj.suiteName'
    },
    {
      Header: 'Repo URL',
      accessor: 'dummyObj.repoUrl'
    },
    {
      Header: 'Repo Branch',
      accessor: 'dummyObj.repoBranch'
    },
    {
      Header: 'Service Name',
      accessor: 'dummyObj.services.0.name'
    },
    {
      Header: 'Simulation Name',
      accessor: 'dummyObj.services.0.simulations.0.name'
    },
    {
      Header: 'Simulation Service',
      accessor: 'dummyObj.services.0.simulations.0.serviceName'
    },
    {
      Header: 'Gatling Version',
      accessor: 'dummyObj.services.0.simulations.0.gatlingVersion'
    },
    {
      Header: 'Load Generator',
      accessor: 'dummyObj.services.0.simulations.0.loadGenerator.label'
    },
    {
      Header: 'Load Generator Type',
      accessor: 'dummyObj.services.0.simulations.0.loadGenerator.type'
    },
    {
      Header: 'Load Generator Beekeeper Protocol',
      accessor: 'dummyObj.services.0.simulations.0.loadGenerator.beekeeperProtocol'
    },
    {
      Header: 'Load Generator Beekeeper URL',
      accessor: 'dummyObj.services.0.simulations.0.loadGenerator.beekeeperUrl'
    },
    {
      Header: 'Load Generator Bee Protocol',
      accessor: 'dummyObj.services.0.simulations.0.loadGenerator.beeProtocol'
    },
    {
      Header: 'Load Generator Bee Port',
      accessor: 'dummyObj.services.0.simulations.0.loadGenerator.beePort'
    },
    {
      Header: 'No. Bees',
      accessor: 'dummyObj.services.0.simulations.0.numberOfBees'
    },
    {
      Header: 'Disable Caching',
      accessor: 'dummyObj.services.0.simulations.0.disableCaching'
    },
    {
      Header: 'Simulation Scenario',
      accessor: 'dummyObj.services.0.simulations.0.simulationsDefinitions.0.scenario'
    },
    {
      Header: 'Simulation Load Injector Name',
      accessor: 'dummyObj.services.0.simulations.0.simulationsDefinitions.0.loadInjector.name'
    },
    {
      Header: 'Simulation Load Injector Variables',
      accessor: 'dummyObj.services.0.simulations.0.simulationsDefinitions.0.loadInjector.injectorVariables'
    },
    {
      Header: 'Simulation Load Injector Steps',
      accessor: 'dummyObj.services.0.simulations.0.simulationsDefinitions.0.loadInjector.injectorSteps'
    },
    {
      Header: 'Data',
      accessor: 'dummyObj.services.data'
    },
    {
      Header: 'PLT Config Test To Run',
      accessor: 'dummyObj.services.pltConfig.TestToRun'
    },
    {
      Header: 'PLT Config Package',
      accessor: 'dummyObj.services.pltConfig.Package'
    },
    {
      Header: 'PLT Config Test Configs',
      accessor: 'dummyObj.services.pltConfig.TestConfigs'
    },
    {
      Header: 'PLT Config Location',
      accessor: 'dummyObj.services.pltConfigLocation'
    },
  ], []);


  return (
    <div className="App">
      <h3>Basic Table using <code>react-table</code></h3>
      {/* <BasicTableComponent /> */}
      {/* <ColapseColTable columns={testColumns} data={data} /> */}
      <FinalTableComponent columns={finalColumns} data={testData} />
    </div>
  );
}

export default App;
